django_scrapy/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from Crawl.views import ScraperAPIView, ScrapedDataListAPIView, download_csv, download_json, home, SignUpView, LoginView, LogoutView, profile_view, data_detail_view, change_password_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('api/signup/', SignUpView.as_view(), name='signup'),
    path('api/login/', LoginView.as_view(), name='login'),
    path('api/logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('change-password/', change_password_view.as_view(), name= 'change-password'),
    path('api/scraper/', ScraperAPIView.as_view(), name='scraper-api'),
    path('api/scraped-data/', ScrapedDataListAPIView.as_view(), name='get-scraped-data'),
    path('api/detail/<int:data_id>', data_detail_view, name='data-detail'),
    path('download-csv/', download_csv, name='download-csv'),  
    path('download-json', download_json, name='download-json'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Crawl/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

class ScrapedData(models.Model):
    data = models.JSONField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.data)
    

Crawl/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User

class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    
class ChangePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    new_password = forms.CharField(widget=forms.PasswordInput)
    new_password_confirmation = forms.CharField(widget=forms.PasswordInput)


class CrawlForm(forms.Form):
    url = forms.URLField(label='URL', widget=forms.URLInput(attrs={'placeholder': 'Enter the URL to scrape'}))
    keys = forms.CharField(label='Keys', widget=forms.Textarea(attrs={'placeholder': 'Enter keys separated by commas'}))
    xpaths = forms.CharField(label='XPaths', widget=forms.Textarea(attrs={'placeholder': 'Enter XPaths separated by commas'}))
    
    

Crawl/views.py
from rest_framework import status, generics
from rest_framework.response import Response
from rest_framework.views import APIView
from django.views import View
from .serializers import ScraperSerializer, DataSerializer, UserSerializer, UserRegisterSerializer, ChangePasswordSerializer
from .scrapy_spider import run_scrapy_spider
from .models import ScrapedData
from django.http import HttpResponse
import pandas as pd
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from rest_framework.permissions import AllowAny, IsAuthenticated
from .forms import SignUpForm, LoginForm, CrawlForm, ChangePasswordForm
from django.contrib import messages
from celery import shared_task




class SignUpView(APIView):
    permission_classes = [AllowAny]
    def get(self, request):
        form = SignUpForm()
        return render(request, 'signup.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            serializer_class = UserRegisterSerializer(data=form.cleaned_data)
            if serializer_class.is_valid():
                serializer_class.save()
                messages.success(request, 'User created successfully')
                user = authenticate(request, username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password'))
                login(request=request, user=user)
                # send_welcome_email(user_id=user.pk)
                return redirect('home')
            else:
                messages.error(request, serializer_class.errors)
        return render(request, 'signup.html', {'form': form})


class LoginView(APIView):
    permission_classes = [AllowAny]
    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', {'form': form})


    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            try:
                user = authenticate(request, username=username, password=password)
            except:
                messages.error(request, message="Invalid username or password")
            if user is not None:
                login(request, user)
                messages.success(request, 'Logged in successfully')
                return redirect('home')
            messages.error(request, 'Invalid credentials')
        return render(request, 'login.html', {'form': form})



class LogoutView(APIView):
    @method_decorator(login_required)
    def get(self, request): 
        logout(request)
        messages.success(request, 'Logged out successfully')
        return redirect('login')

class ScraperAPIView(APIView):
    
    def get(self, request):
        form = CrawlForm()
        return render(request, 'scraper.html', {'form': form})
    @shared_task
    def post(self, request, *args, **kwargs):
        form = CrawlForm(data=request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            keys = form.cleaned_data['keys'].split(',')
            xpaths = form.cleaned_data['xpaths'].split(',')
            user = request.user
            # Run the scrapy spider
            try:
                run_scrapy_spider(url, keys, xpaths, user)
                messages.success(request, 'Scraped successfully')
                return redirect('scraper-api')
            except Exception as e:
                messages.error(request, f'An error occurred: {str(e)}')
                return redirect('scraper-api')
        return render(request, 'scraper.html', {'form': form})


class ScrapedDataListAPIView(generics.ListAPIView):
    queryset = ScrapedData.objects.all()
    serializer_class = DataSerializer


def download_csv(request):
    user = request.user
    try:
        scraped_data_objects = ScrapedData.objects.filter(user=user)
    except TypeError or not user:
        return HttpResponse("Bad Request")
    data_list = [data.data for data in scraped_data_objects]
    df = pd.DataFrame(data_list)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="scraped_data.csv"'
    df.to_csv(response, index=False)
    return response

@login_required
def profile_view(request):
    user = request.user
    scraped_data = ScrapedData.objects.filter(user=user).order_by('-created')
    
    if request.method == 'POST':
        data_id = request.POST.get('data_id')
        if data_id:
            data_to_delete = get_object_or_404(ScrapedData, id=data_id, user=user)
            data_to_delete.delete()
            messages.success(request, 'Data deleted successfully')
            return redirect('profile')
        
    display_data = [
        {
            'id': data.id,
            'data': str(data.data)[:200]
        }
        for data in scraped_data
    ]
    
    if not display_data:
        messages.error(request, "You Don't have any data to display")
        return render(request, 'profile.html')
    else:
        return render(request, 'profile.html', {'scraped_data': display_data})




def download_json(request):
    import json
    user = request.user
    try:
        scraped_data_objects = ScrapedData.objects.filter(user=user)
    except TypeError or not user:
        return HttpResponse("Bad Request")
    data_list = [data.data for data in scraped_data_objects]
    response = HttpResponse(json.dumps(data_list), content_type='application/json')
    return response




def home(request):
    return render(request, 'home.html')





@login_required
def data_detail_view(request, data_id):
    data_instance = get_object_or_404(ScrapedData, id=data_id, user=request.user)
    return render(request, 'data_detail.html', {'data_instance': data_instance})


from django.contrib.auth import update_session_auth_hash

class change_password_view(APIView):
    permission_classes = [IsAuthenticated]
    
    def get(self, request):
        form = ChangePasswordForm()
        return render(request, 'change_password.html', {'form': form})
    
    def post(self, request):
        user = request.user
        form = ChangePasswordForm(request.POST)
        
        if form.is_valid():
            current_password = form.cleaned_data['password']
            new_password = form.cleaned_data['new_password']
            new_password_confirmation = form.cleaned_data['new_password_confirmation']
            
            if not user.check_password(current_password):
                messages.error(request, "Incorrect current password")
                return render(request, 'change_password.html', {'form': form})
            
            if new_password != new_password_confirmation:
                messages.error(request,"Passwords Do Not Match")
                return render(request, 'change_password.html', {'form': form})
            
            
            serializer_class = ChangePasswordSerializer(data={'new_password':new_password})
            if serializer_class.is_valid():
                serializer_class.update(instance=user, validated_data=serializer_class.validated_data)
                update_session_auth_hash(request, user)
                messages.success(request, "Password updated successfully")
                return redirect('home')
            else:
                messages.error(request, serializer_class.errors)

        return render(request, 'change_password.html', {'form': form})

Crawl/templates/change_password.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Change Password</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
</head>
<body>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    <h1>Change Password</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change</button>
    </form>
    <a href="{% url 'home' %}">Back to home Login</a>
</body>
</html>

Crawl/templates/data_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Data Detail</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
</head>
<body>
    <h1>Data Detail</h1>
    <p><strong>Data:</strong></p>
    <pre>{{ data_instance.data }}</pre>
    <a href="{% url 'profile' %}">Back to Profile</a>
</body>
</html>

Crawl/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
</head>
<body>
    <h1>Scrap them!</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">
            <button>Logout</button>
        </a>
    {% else %}
        <a href="{% url 'signup' %}">
            <button>Sign Up</button>
        </a>
        <a href="{% url 'login' %}">
            <button>Login</button>
        </a>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'scraper-api' %}">
            <button>Crawl</button>
        </a>
        <a href="{% url 'profile' %}">
            <button>Your Data</button>
        </a>
        <a href="{% url 'change-password' %}">
            <button>Change Password</button>
        </a>
    {% endif %}
</body>
</html>

Crawl/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
</head>
<body>
    <h1>Login</h1>
        {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
        <button>
            <a href="{% url 'home' %}">Back to Home</a>
        </button>
    </form>
    <a href="{% url 'signup' %}">Don't have an account? Sign Up</a>
</body>
</html>

Crawl/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}">
</head>
<body>
    <h1>Your Scraped Data</h1>
    {% if messages %}
        {% for message in messages %}
            <div class="message">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <table class="grid">
        <thead>
            <tr>
                <th>Data</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="grid">
            {% for data in scraped_data %}
                <div >
                    <tr>
                        <td>
                            {{ data.data }}{% if data.data|length > 200 %}...{% endif %}
                        </td>
                        <td>
                        <div class="biu">
                            <div>
                                <a href="{% url 'data-detail' data.id %}">
                                <button type="submit"> Detail</button>
                                </a>
                            </div>
                            <form method="post" action="{% url 'profile' %}">
                                {% csrf_token %}
                                <input type="hidden" name="data_id" value="{{ data.id }}">
                                <button type="submit">Delete</button>
                                    </div>
                                </div>
                            </form>
                        </td>
                    </tr>
                </div>
            {% endfor %}
        </tbody>
    </table>
    <div class="biu">
        <a href="{% url 'download-csv' %}">
            <button>Download Csv</button>
        </a>
        <a href="{% url 'download-json' %}">
            <button>Get JSON</button>
        </a>
    </div>
    <a href="{% url 'home' %}">Back to Home</a>
</body>
</html>

Crawl/templates/scraper.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Scrape Data</title>
    <link rel="stylesheet" type="text/css" href="{% static 'scraper.css' %}">
</head>
<body>
    <div class="container">
        <h1>Scrape Data</h1>
        <form method="post" class="scraper-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_url">URL:</label>
                {{ form.url }}
            </div>
            <div class="form-group">
                <label for="id_keys">Keys:</label>
                {{ form.keys }}
            </div>
            <div class="form-group">
                <label for="id_xpaths">XPaths:</label>
                {{ form.xpaths }}
            </div>
            <button type="submit" class="btn">Start Scraping</button>
        </form>
        <div class="messages">
            <a href="{% url 'home' %}">
                <button>Back to Home</button>
            </a>
            {% if messages %}
                {% for message in messages %}
                    <div class="message {{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

</body>
</html>

Crawl/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
</head>
<body>
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
    <a href="{% url 'login' %}">Already have an account? Login</a>
</body>
</html>